a = int(input())
b = int(input())
print("%6s"%(a))
print("%6s"%(" x "+str(b)))
print("------")
print("%6s"%(a*((b//1)%10)))
print("%5s"%(a*((b//10)%10)))
print("%4s"%(a*((b//100)%10)))
print("------")
print("%6s"%(a*b))